mirte:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20  

  mobile_base_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: 'joint_left_wheel'
    right_wheel: 'joint_right_wheel'
    publish_rate: 50.0 # default: 50
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation: 1.0
    wheel_radius: 0.3
    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier: 1.0 # default: 1.0
    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.5
    # Base frame_id
    base_frame_id: base_footprint #default: base_link
    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits: false
        max_velocity: 1.0 # m/s
        min_velocity: -1 # m/s
        has_acceleration_limits: false
        max_acceleration: 0.8 # m/s^2
        min_acceleration: -0.4 # m/s^2
        has_jerk_limits: false
        max_jerk: 5.0 # m/s^3
    angular:
      z:
        has_velocity_limits: false
        max_velocity: 1.7 # rad/s
        has_acceleration_limits: false
        max_acceleration: 1.5 # rad/s^2
        has_jerk_limits: false
        max_jerk: 2.5 # rad/s^3
        # joint_state_controller:
        #   type: joint_state_controller/JointStateController
        #   publish_rate: 50  
#   # Position Controllers ---------------------------------------

# joint1_position_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: joint_left_wheel
#   pid: {p: 100.0, i: 0.01, d: 10.0}
# joint2_position_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: joint_right_wheel
#   pid: {p: 100.0, i: 0.01, d: 10.0}
